### ISSUE TITLE
(readonly) vault | todo

### ISSUE THREAD

**Issue by sh1kxrv** [xafxafxaf/xaf-vault#1]
## Stages
- [ ] Stage `1` | MVP | Interface-type: `CLI`
   - [ ] CLI
   - [ ] Crypto-library
   - [x] Commands Handler
   - [ ] Logger
- [ ] Stage `2` | Interface-type: `WEB-UI`
   - [ ] design `vault`
   - [ ] develop repository @vault/web-ui ( vue3/react + tauri/electron )

## MVP
- [ ] SQL-Builder | @vault/sql
   - [ ] Fundamental Instructions like `SELECT`, `INSERT`, `UPDATE`, etc.
   - [ ] Fundamental Condition-Instructions like `WHERE`, `ORDER BY`, etc. 
   - [ ] Validation `?`
- [ ] ...

## Functions
- [ ] OpenAPI Codegen | API generation
- [ ] `Any` Data Storage | With encryption
- [ ] ...
